@startuml

'------------------
' INTERFACES
'------------------

interface IPlayer {
    void yourTurn()
    String getName()
    void newGame(int min, int max, String opponent, String type)
    boolean endOfGame(int numberOfGuesses, String opponent)
}

interface IGuesser {
    int makeGuess()
    void guessFeedback(Answer answer)
}

interface IThinker {
    Answer evaluateGuess(int guess, String opponent)
}

'------------------
' ABSTRACT CLASSES
'------------------

abstract class AComputerPlayer {
    + void yourTurn()
    + boolean endOfGame(int numberOfGuesses, String opponent)
}

abstract class AHumanPlayer {
    # static final Scanner scanner
    - String name
    + AComputerPlayer()
    + void yourTurn()
    + String getName()
    + void newGame(int min, int max, String opponent, String type)
    # boolean playAgain()
}

'------------------
' CLASSES
'------------------

class ComputerThinker {
    - int secretNumber
    + String getName()
    + void newGame(int min, int max, String opponent, String type)
    + Answer evaluateGuess(int guess, String opponent)
}

class ComputerGuesser {
    - int min
    - int max
    + String getName()
    + void newGame(int min, int max, String opponent, String type)
    + int makeGuess()
    + void guessFeedback(Answer answer)
}

class HumanThinker {
    + Answer evaluateGuess(int guess, String opponent)
    + boolean endOfGame(int numberOfGuesses, String opponent)
}

class HumanGuesser {
    + int makeGuess()
    + void guessFeedback(Answer answer)
    + boolean endOfGame(int numberOfGuesses, String opponent)
}

class GameControl {
    - final int min
    - final int max
    + GameControl(int min, int max)
    + void runGame(IPlayer thinker, IPlayer guesser)
}

class Main {
    - static Scanner scanner
    + static void main(String[] args)
    + static int chooseType(String s)
}

'------------------
' ENUMS
'------------------

enum Answer {
    TOO_LOW
    TOO_HIGH
    CORRECT
}

'------------------
' RELATIONS
'------------------

Main *-- GameControl

GameControl *-- IPlayer

IPlayer <|.. IThinker
IPlayer <|.. IGuesser

ComputerThinker <|.. IPlayer
ComputerGuesser <|.. IPlayer
HumanThinker <|.. IPlayer
HumanGuesser <|.. IPlayer

AComputerPlayer <|-- ComputerThinker
AComputerPlayer <|-- ComputerGuesser
AHumanPlayer <|-- HumanThinker
AHumanPlayer <|-- HumanGuesser

@enduml