@startuml
'https://plantuml.com/class-diagram

abstract class AComputerPlayer
abstract class AHumanPlayer
interface IGuesser
interface IThinker

class ComputerThinker {
}

class ComputerGuesser {
}

class HumanThinker {
}

class HumanGuesser {
}

class GameControl {
}

class Main {
}

enum Answer {
    TOO_LOW
    TOO_HIGH
    CORRECT
}

@enduml